name: Build V2

on: 
  workflow_dispatch:
  push:
    branches:
      - v2
    paths-ignore:
      - '.github/workflows/*'
      - '*.md'
      - '.gitignore'

jobs:
  build:
    runs-on: windows-latest
    env:
      GOOS: "windows"
      GOARCH: "amd64"
      
    steps:
    - uses: actions/checkout@v3.6.0
      with:
        ref: v2
    
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 7
        run_install: false          
          
    - name: Install go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.13.1'
          
    - name: build AHK
      uses: CCCC-L/Action-Ahk2Exe@v1.0.0
      with:
        in: Launcher.ahk
   
    - name: build vue
      shell: pwsh
      run: |
        cd ./config-ui
        npm install
        npm run build
        # 删除多于字体
        Get-ChildItem -Path ./dist/assets -Include *.woff,*.eot,*.ttf -File -Recurse | rm

    - name: build go
      shell: pwsh
      run: |
        cd ./config-server
        go build -ldflags "-s -w" ./cmd/settings
      
    - name: copy files
      shell: pwsh
      run: |
        mkdir MyKeymap
        cp -r -Force ./bin ./Mykeymap
        cp -r -Force ./data ./Mykeymap
        cp -r -Force ./tools ./Mykeymap

        cp -Force ./MyKeymap.exe ./Mykeymap
        cp -Force ./config-server/settings.exe ./Mykeymap/bin
        cp -r -Force ./config-server/templates ./Mykeymap/bin/
        cp -Force ./config-ui/index.html ./Mykeymap/bin/templates
        cp -r -Force ./config-ui/dist ./Mykeymap/bin/site

    - uses: actions/upload-artifact@master
      with:
        name: MyKeymap
        path: MyKeymap
